server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: EurekaClient
        uri: http://localhost:9093/
        predicates:
        - Path=/eureka/**